name: Deploy website to Heroku
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # git clone
      - name: Clone
        uses: actions/checkout@v2
      # linter
      - name: Linter
        uses: michaelw90/PHP-Lint@master
      # security check
      - name: Security check
        uses: symfonycorp/security-checker-action@v2
      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
          with:
            args: analyse src/
      - name: Deploy Heroku
        uses: akhileshns/heroku-deploy@v3.5.6 # This is the action
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: ${{secrets.HEROKU_APP}} #Must be unique in Heroku
            heroku_email: ${{secrets.HEROKU_EMAIL}}
